version: '3.5'
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=genadminpwd
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
  backend:
    image: malekbenabdellatife/achat
    container_name: achat
    ports:
      - 8089:8089
    volumes:
      - .m2:/root/.m2
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
volumes:
  db:
  .m2: